create table T_mysql_generate_test
(
    id             bigint auto_increment primary key comment 'pk',
    tinyint_col    tinyint,
    smallint_col   smallint,
    mediumint_col  mediumint,
    int_col        int,
    bigint_col     bigint,
    decimal_col    decimal(10, 2),
    float_col      float,
    double_col     double,
    bit_col        bit(1),
    date_col       date,
    datetime_col   datetime,
    timestamp_col  timestamp default current_timestamp,
    time_col       time,
    year_col       year,
    char_col       char(50),
    varchar_col    varchar(255),
    text_col       text,
    mediumtext_col mediumtext,
    longtext_col   longtext,
    tinytext_col   tinytext,
    blob_col       blob,
    mediumblob_col mediumblob,
    longblob_col   longblob,
    json_col       json,
    enum_col       enum ('value1', 'value2', 'value3'),
    set_col        set ('value1', 'value2', 'value3'),
    geometry_col   geometry,
    point_col      point,
    linestring_col linestring,
    polygon_col    polygon
);
