services:
    arale.codegen.api:
        image: arale.codegen.api
        build:
            context: .
            dockerfile: Arale.CodeGen.Api/Dockerfile
        ports:
            - "18080:8080"
            - "18081:8081"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        volumes:
            - /home/shiloh/projects/arale-codegen/be:/app
        user: 1000:1000
