services:
    arale.codegen.api:
        user: "1000:1000"
        image: arale.codegen.api
        build:
            context: .
            dockerfile: Arale.CodeGen.Api/Dockerfile
        ports:
            - "18080:8080"
            - "18081:8081"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - APP_UID=1000
        volumes:
            - arale_codegen:/app

volumes:
    arale_codegen:
