name: Deploy API

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ 'ui/**', '*.md', '.github/workflows/**' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: HuaweiCloud
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: Arale.CodeGen
          file: Arale.CodeGen/Arale.CodeGen.Api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/arale.codegen.api:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop arale.codegen.api || true
            docker rm arale.codegen.api || true
            docker image rm ${{ secrets.DOCKER_HUB_USERNAME }}/arale.codegen.api:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/arale.codegen.api:latest
            docker run -d --name arale.codegen.api -p 18080:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/arale.codegen.api:latest
